### ISSUE TITLE
Sync or Poll - Problem

### ISSUE THREAD

**Issue by steady286** [bpeel/notbit#21]
Hello Neil,

i noticed, that after a while the Notbit process uses 100% of cpu time, and there are not further messages received. Investigation with "valgrind" and "gdb" shows me, that the main process is polling a lot, all other processes idle at "pthread_cond_wait".

I attach a thread backtrace of a process in the named situation, and a callgrind tracer from another process, also in that situation.

Does this help?

[backtrace.txt](https://github.com/bpeel/notbit/files/3317545/backtrace.txt)
[callgrind.out.14360.txt](https://github.com/bpeel/notbit/files/3317546/callgrind.out.14360.txt)

I am on commit 5cdb2396860c6.
Thanks, Gerhard

**Comment by bpeel** [comment]
This is likely to be fixed with [this commit](https://github.com/bpeel/notbit/commit/ecaa3e6d8a121d198cebc0ffe8e39386bd914d07). Thanks for reporting it.
