### ISSUE TITLE
Serious problem in check_timer_sources() of ntb_main_context.c - Infinite loop, 100% CPU, non-working state

### ISSUE THREAD

**Issue by olext** [bpeel/notbit#24]
There is a logic fatal error in code:
```
        ntb_list_for_each_safe(source, tmp_source, &to_emit, link) {
                if (source->removed) {
                        free_source(mc, source);
                } else {
                        ntb_list_insert(&source->bucket->sources,
                                        &source->link);
                        source->busy = false;
                }
        }
```
Problem is that if remove happened during callback above there is a collision situation of removing from list (free_source -> ntb_list_remove) and ntb_list_insert(). Because ntb_list_insert does not care about current list to_emit then ntb_listr_remove follow pointers of to_emit and distort list bucket->sources.

As result bucket->sources became broken with small sub-coils which leads to infinite loop during next for_each via bucket->sources and program became unresponsible, 100% CPU, but for user it is no indication of something wrong.

I suggest to split it into two loops, first one ntb_list_for_each_safe which can do removal
and second loop to perform reinserts into bucket->sources. It looks like you can not combine these two operations same time in one loop.

Like this:

```
        ntb_list_for_each_safe(source, tmp_source, &to_emit, link) {
                if (source->removed) {
                        free_source(mc, source);
                }
        }
        ntb_list_for_each_safe(source, tmp_source, &to_emit, link) {
                        ntb_list_insert(&source->bucket->sources,
                                        &source->link);
                        source->busy = false;
        }
```

**Comment by bpeel** [comment]
Thanks for looking into this and describing the problem in detail. Presumably this is the same problem as in issue #21.

The fix looks good to me. I think an alternative fix could be to just call `ntb_list_remove(&source->link)` just before calling `ntb_list_insert`. That way I guess it would be less code, but perhaps your approach would technically be faster. Another idea could be to have an alternative version of `free_source` that doesn’t call `ntb_list_remove`, because there isn’t really any point in removing things from the `to_emit` list. Perhaps it could be done with an argument to avoid repeating the code like this:

```C
static void
free_source_with_remove(struct ntb_main_context *mc,
                        struct ntb_main_context_source *source,
                        bool remove)
{
        pthread_mutex_lock(&mc->idle_mutex);
        if (remove)
                ntb_list_remove(&source->link);
        ntb_slice_free(&mc->source_allocator, source);
        pthread_mutex_unlock(&mc->idle_mutex);
}

static void
free_source(struct ntb_main_context *mc,
            struct ntb_main_context_source *source)
{
        free_source_with_remove(mc, source, true);
}

static void
check_timer_sources(struct ntb_main_context *mc)
{
        /* … */
        ntb_list_for_each_safe(source, tmp_source, &to_emit, link) {
                if (source->removed) {
                        free_source_with_remove(mc, source, false);
                } else {
                        ntb_list_insert(&source->bucket->sources,
                                        &source->link);
                        source->busy = false;
                }
        }
}
```

What do you think?

**Comment by olext** [comment]
To my mind it is safer to have two loops - for the point of code maintenance with appropriate comment why the remove requires additional loop. As this situation in reality happens only about once or few times per day - so it was actually hard to catch and then it was hard to get step-by-step into the appropriate source of the problem. So with thinking about protecting future code edits from similar culpit it is better to have it separate as intentions of writing this code block in this way is easy to be forgotten in future.

**Comment by olext** [comment]
I created merge request #25 (I see i created issue from another work account :) ) which I can expand with comment about the purpose of the loop. Or you may wish to change code yourself, it is small fix as the cause is caught.

**Comment by yshurik** [comment]
Hi, any chance to accept the merge request or push your fix? The official notbit repository still has the problem unpatched.

**Comment by bpeel** [comment]
Sorry for the delay. I decided to [go with the option](https://github.com/bpeel/notbit/commit/ecaa3e6d8a121d198cebc0ffe8e39386bd914d07) of just calling `ntb_list_remove(&source->link)`. Thanks again for looking into this.
