### ISSUE TITLE
Error connecting to IPC socket: No such file or directory

### ISSUE THREAD

**Issue by sac001** [bpeel/notbit#27]
Hi,

I do have notbit running on my VPS server with a postfix mail server and used already notbit with a simple hack as an mail2chan Gateway successfully. However this simple hack stores email messages temporarly prior they get with 'cat' piped to notbit-sendmail. I like to avoid the file saving and 'cat' and tried many many things already which leads always to an error.

I use procmail, which calls an example shell script, which looks like this:

#!/usr/bin/env -S bash -x
cat - | /usr/bin/sed -n '/---Begin Bitmessage---/,/---End Bitmessage---/{//!p}' \
| xargs /usr/bin/echo | /home/mail2chan/bin/notbit-sendmail

The message body content of an email I send to my Gateway looks like this:

---Begin Bitmessage---
From: BM-2cWFkyuXXFw6d393RGnin2RpSXj8wxtt6F@bitmessage
To: BM-2cWFkyuXXFw6d393RGnin2RpSXj8wxtt6F@bitmessage
Subject: test #4

d
---End Bitmessage---

The procmail log gives then this error:

From me@example.com  Fri Sep 10 17:56:11 2021
 Subject: test
  Folder: /home/mail2chan/script.sh                                              1781
procmail: Executing "/home/mail2chan/script.sh"
+ xargs /usr/bin/echo
+ /home/mail2chan/bin/notbit-sendmail
+ /usr/bin/sed -n '/---Begin Bitmessage---/,/---End Bitmessage---/{//!p}'
+ cat -
Error connecting to IPC socket: No such file or directory
xargs: /usr/bin/echo: terminated by signal 13

Regardsless what scripts I tried I always get this IPC socket error.

Any help to fix this issue would be greatly appreciated.

Best regards
Stefan

**Comment by bpeel** [comment]
Could it be that your procmail server is running under a different user than notbit? notbit-sendmail communicates with the notbit server using a unix-domain socket. It generates the name for this using either the value of `$XDG_RUNTIME_DIR` or if that isn’t set it will [generate a path](https://github.com/bpeel/notbit/blob/master/src/ntb-ipc-sockaddr.c#L38) with the UID in it. That means the path will be different for each user on the system. You could maybe fix this by setting `$XDG_RUNTIME_DIR` to the same value in both your procmail server and notbit.

**Comment by yshurik** [comment]
As a bit different solution you may use notbit with smtp patch

**Comment by sac001** [comment]
@bpeel Thanks for your help and yes they both run under a different user. I will try out your advise.
@yshurik Thanks, but I like to stay with the original version for now.

**Comment by sac001** [comment]
Small update. A friend suggested a symbolic link and I did the following then:
ln -s /run/user/1000/notbit/notbit-ipc /temp/notbit-1000/notbit-ipc and now
the procmail script works perfect with notbit-sendmail under different users.
