### ISSUE TITLE
Support for protocol v3?

### ISSUE THREAD

**Issue by kseistrup** [bpeel/notbit#9]
“All objects sent on the network should support protocol v3 starting on Sun, 16 Nov 2014 22:00:00 GMT.”

https://bitmessage.org/wiki/Protocol_specification

Will notbit support protocol v3?

**Comment by Maesto** [comment]
I would love to. But this code has a fraction of the comments I would consider nessesary to understand this codebase securely enough. Comments for each function about what it does and what it's purpose is would be a minimum.

**Comment by kseistrup** [comment]
I'd say that `notbit` has been abandoned… Ciao.

**Comment by rubo77** [comment]
I added a first generated documentation with doxygen here: https://github.com/bpeel/notbit/pull/11

see also http://stackoverflow.com/a/34409287/1069083

**Comment by bpeel** [comment]
I finally got around to doing this.
https://github.com/bpeel/notbit/commit/36bdc82aeebc84948f54143551099834dfd55fee
